name: Deploy to development

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    name: Deploying everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem root@64.227.156.142 << 'EOF'
            cd ci-cd-turborepo/
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart web
            pm2 restart http
            pm2 restart ws
          EOF

